name: Generate xml sitemap

on:
  push:
    branches: [ main ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
    - name: Checkout the main branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 
        token: ${{ secrets.GH_PAT }}
        path: main

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://theanlim.github.io/puat_ah/
        path-to-root: main

    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages

    - name: Move sitemap to gh-pages branch
      run: |
        cp main/${{ steps.sitemap.outputs.sitemap-path }} gh-pages/

    - name: Commit and push changes
      run: |
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add sitemap"
        git push origin gh-pages
