name: Generate xml sitemap

on:
  push:
    branches: [ main ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 
        token: ${{ secrets.GH_PAT }}

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://theanlim.github.io/puat_ah/

    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"

    - name: Checkout gh-pages branch
      run: |
        git fetch origin gh-pages:gh-pages
        git checkout gh-pages

    - name: Print current directory
      run: pwd

    - name: List files in current directory
      run: ls -la

    - name: Print sitemap path
      run: echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"

    - name: Move sitemap to gh-pages branch
      run: |
        mv ${{ steps.sitemap.outputs.sitemap-path }} .

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add sitemap"
        git push origin gh-pages
